/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSurveyIdRouteImport } from './routes/s.$surveyId'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppPricingRouteImport } from './routes/_app.pricing'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppSurveysNewRouteImport } from './routes/_app.surveys.new'
import { Route as AppSurveysIdAnalyticsRouteImport } from './routes/_app.surveys.$id.analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSurveyIdRoute = SSurveyIdRouteImport.update({
  id: '/s/$surveyId',
  path: '/s/$surveyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSurveysNewRoute = AppSurveysNewRouteImport.update({
  id: '/surveys/new',
  path: '/surveys/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSurveysIdAnalyticsRoute = AppSurveysIdAnalyticsRouteImport.update({
  id: '/surveys/$id/analytics',
  path: '/surveys/$id/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/ai': typeof AppAiRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/pricing': typeof AppPricingRoute
  '/team': typeof AppTeamRoute
  '/s/$surveyId': typeof SSurveyIdRoute
  '/surveys/new': typeof AppSurveysNewRoute
  '/surveys/$id/analytics': typeof AppSurveysIdAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/ai': typeof AppAiRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/pricing': typeof AppPricingRoute
  '/team': typeof AppTeamRoute
  '/s/$surveyId': typeof SSurveyIdRoute
  '/surveys/new': typeof AppSurveysNewRoute
  '/surveys/$id/analytics': typeof AppSurveysIdAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/pricing': typeof AppPricingRoute
  '/_app/team': typeof AppTeamRoute
  '/s/$surveyId': typeof SSurveyIdRoute
  '/_app/surveys/new': typeof AppSurveysNewRoute
  '/_app/surveys/$id/analytics': typeof AppSurveysIdAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/ai'
    | '/billing'
    | '/dashboard'
    | '/pricing'
    | '/team'
    | '/s/$surveyId'
    | '/surveys/new'
    | '/surveys/$id/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/ai'
    | '/billing'
    | '/dashboard'
    | '/pricing'
    | '/team'
    | '/s/$surveyId'
    | '/surveys/new'
    | '/surveys/$id/analytics'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/ai'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/pricing'
    | '/_app/team'
    | '/s/$surveyId'
    | '/_app/surveys/new'
    | '/_app/surveys/$id/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SSurveyIdRoute: typeof SSurveyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$surveyId': {
      id: '/s/$surveyId'
      path: '/s/$surveyId'
      fullPath: '/s/$surveyId'
      preLoaderRoute: typeof SSurveyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing': {
      id: '/_app/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/surveys/new': {
      id: '/_app/surveys/new'
      path: '/surveys/new'
      fullPath: '/surveys/new'
      preLoaderRoute: typeof AppSurveysNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/surveys/$id/analytics': {
      id: '/_app/surveys/$id/analytics'
      path: '/surveys/$id/analytics'
      fullPath: '/surveys/$id/analytics'
      preLoaderRoute: typeof AppSurveysIdAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAiRoute: typeof AppAiRoute
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPricingRoute: typeof AppPricingRoute
  AppTeamRoute: typeof AppTeamRoute
  AppSurveysNewRoute: typeof AppSurveysNewRoute
  AppSurveysIdAnalyticsRoute: typeof AppSurveysIdAnalyticsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAiRoute: AppAiRoute,
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPricingRoute: AppPricingRoute,
  AppTeamRoute: AppTeamRoute,
  AppSurveysNewRoute: AppSurveysNewRoute,
  AppSurveysIdAnalyticsRoute: AppSurveysIdAnalyticsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SSurveyIdRoute: SSurveyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
